title: Nathan Chang 
email: 
url: "https://n8cha.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: ""
github_username: n8cha 

# Build settings
remote_theme: n8cha/colorieretro

google_analytics: G-ZW7YBBVWJ7

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug
